// Code generated by MockGen. DO NOT EDIT.
// Source: repository/interfaces.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	models "github.com/SawitProRecruitment/UserService/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockEstateRepository is a mock of EstateRepository interface.
type MockEstateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEstateRepositoryMockRecorder
}

// MockEstateRepositoryMockRecorder is the mock recorder for MockEstateRepository.
type MockEstateRepositoryMockRecorder struct {
	mock *MockEstateRepository
}

// NewMockEstateRepository creates a new mock instance.
func NewMockEstateRepository(ctrl *gomock.Controller) *MockEstateRepository {
	mock := &MockEstateRepository{ctrl: ctrl}
	mock.recorder = &MockEstateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEstateRepository) EXPECT() *MockEstateRepositoryMockRecorder {
	return m.recorder
}

// CreateEstate mocks base method.
func (m *MockEstateRepository) CreateEstate(ctx context.Context, width, length int) (*models.Estate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEstate", ctx, width, length)
	ret0, _ := ret[0].(*models.Estate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEstate indicates an expected call of CreateEstate.
func (mr *MockEstateRepositoryMockRecorder) CreateEstate(ctx, width, length interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEstate", reflect.TypeOf((*MockEstateRepository)(nil).CreateEstate), ctx, width, length)
}

// CreateTree mocks base method.
func (m *MockEstateRepository) CreateTree(ctx context.Context, estateID uuid.UUID, x, y, height int) (*models.Tree, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTree", ctx, estateID, x, y, height)
	ret0, _ := ret[0].(*models.Tree)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTree indicates an expected call of CreateTree.
func (mr *MockEstateRepositoryMockRecorder) CreateTree(ctx, estateID, x, y, height interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTree", reflect.TypeOf((*MockEstateRepository)(nil).CreateTree), ctx, estateID, x, y, height)
}

// GetEstate mocks base method.
func (m *MockEstateRepository) GetEstate(ctx context.Context, id uuid.UUID) (*models.Estate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEstate", ctx, id)
	ret0, _ := ret[0].(*models.Estate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEstate indicates an expected call of GetEstate.
func (mr *MockEstateRepositoryMockRecorder) GetEstate(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEstate", reflect.TypeOf((*MockEstateRepository)(nil).GetEstate), ctx, id)
}

// GetTreesByEstate mocks base method.
func (m *MockEstateRepository) GetTreesByEstate(ctx context.Context, estateID uuid.UUID) ([]models.Tree, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTreesByEstate", ctx, estateID)
	ret0, _ := ret[0].([]models.Tree)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTreesByEstate indicates an expected call of GetTreesByEstate.
func (mr *MockEstateRepositoryMockRecorder) GetTreesByEstate(ctx, estateID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTreesByEstate", reflect.TypeOf((*MockEstateRepository)(nil).GetTreesByEstate), ctx, estateID)
}
